Repository kubernetes-sigs/yaml, pull requests merged in 2018-11, with the labels that each got.

#3 Add OWNERS and other template files
  CONTRIBUTING.md
  OWNERS
  RELEASE.md
  SECURITY_CONTACTS
  code-of-conduct.md
Labels: cncf-cla: yes, size/M

#2 Add test for multiple keys
  yaml_test.go
Labels: cncf-cla: yes, lgtm, size/M

#6 Update .travis.yml with additional checks
  .travis.yml
  fields.go
  yaml.go
  yaml_go110_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5 UnmarshalStrict: use DisallowUnknownFields
  yaml.go
  yaml_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S
