Repository kubernetes-sigs/yaml, pull requests merged in 2021-01, with the labels that each got.

#42 yaml_test: adapt around undefined behavior in float64->int64 casting
  yaml_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/backlog, sig/api-machinery, size/XS

#50 added github-actions CI
  .github/workflows/go.yml
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/M

#51 removed go v1.12.x and added go v1.15.x in github-actions ci
  .github/workflows/go.yml
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/XS

#44 Add CI tests for ARM64
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/XS
